version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker123
      MYSQL_DATABASE: parking
      MYSQL_USER: docker123
      MYSQL_PASSWORD: docker123
    ports:
      - "3306:3306"